package Runner;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AA
 */
public class runnerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public runnerDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewTask = new javax.swing.JButton();
        AcceptTask = new javax.swing.JButton();
        DeclineTask = new javax.swing.JButton();
        UpdateStatus = new javax.swing.JButton();
        CheckTaskHistory = new javax.swing.JButton();
        CustomerReview = new javax.swing.JButton();
        RevenueDashboard = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ViewTask.setText("View Task");
        ViewTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTaskActionPerformed(evt);
            }
        });

        AcceptTask.setText("Accept Task");
        AcceptTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptTaskActionPerformed(evt);
            }
        });

        DeclineTask.setText("Decline Task");
        DeclineTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeclineTaskActionPerformed(evt);
            }
        });

        UpdateStatus.setText("Update Task Status");
        UpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateStatusActionPerformed(evt);
            }
        });

        CheckTaskHistory.setText("Check Task History");
        CheckTaskHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckTaskHistoryActionPerformed(evt);
            }
        });

        CustomerReview.setText("Read Customer Review");
        CustomerReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerReviewActionPerformed(evt);
            }
        });

        RevenueDashboard.setText("Show Revenue Dashboard");
        RevenueDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevenueDashboardActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Delivery Runner Dashboard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateStatus, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(AcceptTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DeclineTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RevenueDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CustomerReview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CheckTaskHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ViewTask)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AcceptTask)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DeclineTask))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CheckTaskHistory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CustomerReview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RevenueDashboard)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UpdateStatus)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTaskActionPerformed
        ViewTask viewtask = new ViewTask();
        this.setVisible(false);
        viewtask.setVisible(true);
    }//GEN-LAST:event_ViewTaskActionPerformed

    private void CheckTaskHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckTaskHistoryActionPerformed
        CheckTaskHistory checktaskhistory = new CheckTaskHistory();
        this.setVisible(false);
        checktaskhistory.setVisible(true);
    }//GEN-LAST:event_CheckTaskHistoryActionPerformed

    private void AcceptTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptTaskActionPerformed
        AcceptTask accepttask = new AcceptTask();
        this.setVisible(false);
        accepttask.setVisible(true);
    }//GEN-LAST:event_AcceptTaskActionPerformed

    private void DeclineTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeclineTaskActionPerformed
        DeclineTask declinetask = new DeclineTask();
        this.setVisible(false);
        declinetask.setVisible(true);
    }//GEN-LAST:event_DeclineTaskActionPerformed

    private void UpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateStatusActionPerformed
         UpdateStatus updatestatus = new UpdateStatus();
        this.setVisible(false);
        updatestatus.setVisible(true);
    }//GEN-LAST:event_UpdateStatusActionPerformed

    private void CustomerReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerReviewActionPerformed
        CustomerReview customerreview = new CustomerReview();
        this.setVisible(false);
        customerreview.setVisible(true);
    }//GEN-LAST:event_CustomerReviewActionPerformed

    private void RevenueDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevenueDashboardActionPerformed
        runnerRevenueDashboard revenuedashboard = new runnerRevenueDashboard();
        this.setVisible(false);
        revenuedashboard.setVisible(true);
    }//GEN-LAST:event_RevenueDashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(runnerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(runnerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(runnerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(runnerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new runnerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptTask;
    private javax.swing.JButton CheckTaskHistory;
    private javax.swing.JButton CustomerReview;
    private javax.swing.JButton DeclineTask;
    private javax.swing.JButton RevenueDashboard;
    private javax.swing.JButton UpdateStatus;
    private javax.swing.JButton ViewTask;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
