/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Manager;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DreamDreams
 */
public class managerDiscardItems extends javax.swing.JFrame {

    /**
     * Creates new form managerDiscardItems
     */
    public managerDiscardItems() {
        initComponents();
        refreshData();
    }

  
       public void refreshData(){
        try{
        DefaultTableModel model = (DefaultTableModel) managerItemInspectionTable.getModel();
        model.setRowCount(0);
        
        //reading file
        
        String filename = "menuitems.txt";
        BufferedReader br = new BufferedReader(new FileReader(filename));
        String line;
        
        while((line = br.readLine())!= null){
            String[] data = line.split(";");
                      
            model.addRow(new Object[]{
                data[1],data[2]
            });
          }  
        
        }catch(IOException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        managerItemInspectionTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        vendorDeleteBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        managerItemInspectionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price"
            }
        ));
        jScrollPane1.setViewportView(managerItemInspectionTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("Vendor Item Inspection");

        vendorDeleteBtn.setBackground(new java.awt.Color(255, 102, 102));
        vendorDeleteBtn.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        vendorDeleteBtn.setForeground(new java.awt.Color(0, 0, 0));
        vendorDeleteBtn.setText("Delete");
        vendorDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorDeleteBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(vendorDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1)))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(vendorDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vendorDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorDeleteBtnActionPerformed
      {                                          
//delete selected row in table
        try{
            String filepath = "menuitems.txt";
          int SelectedRow = managerItemInspectionTable.getSelectedRow();
          if(SelectedRow != -1){
              DefaultTableModel model = (DefaultTableModel) managerItemInspectionTable.getModel();
              model.removeRow(SelectedRow);
              JOptionPane.showMessageDialog(null, "Itme Deleted!");
          }else{
              JOptionPane.showMessageDialog(null, "No Item selected");
          }
      //deleting selected row in file
      //reading lines from the file

          BufferedReader br = new BufferedReader(new FileReader(filepath));
          StringBuilder filecontent = new StringBuilder();
          String line;

          //counter of index starting from 0 when rows are selected
          int currentLineIndex = 0;

          while((line =br.readLine()) != null ){
              //we save the lines that aren't selected
              //if the current line index matches the selectedRow index, we skip the if block and only +1 currentLineIndex
              if(currentLineIndex != SelectedRow){
                  filecontent.append(line).append("\n");
              }
              currentLineIndex++;
          }
          br.close();
          //writng the content into the file
          FileWriter fw = new FileWriter(filepath);
          fw.write(filecontent.toString());
          fw.close();
          
          refreshData();
      }catch(IOException e){
          JOptionPane.showMessageDialog(null,e.getMessage());
      }catch(Exception e){
          JOptionPane.showMessageDialog(null, e.getMessage());
      }


    }                  
    }//GEN-LAST:event_vendorDeleteBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new managerHomePage().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managerDiscardItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managerDiscardItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managerDiscardItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managerDiscardItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managerDiscardItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable managerItemInspectionTable;
    private javax.swing.JButton vendorDeleteBtn;
    // End of variables declaration//GEN-END:variables
}
